// The pure part of `vendor-edge-packages.js`: what the vendored copy of a
// package source should contain, and where a set of vendored files has drifted
// from the sources they were copied from. The CLI does the filesystem I/O and
// calls these.

/** The "do not edit" banner prepended to every vendored file. */
export const HEADER =
  '// GENERATED by scripts/vendor-edge-packages.js — do not edit.\n' +
  '// Source of truth: packages/%PKG%/src/%FILE%. Run `pnpm vendor:edge` after\n' +
  '// changing the package, or CI (`pnpm check:vendor-edge`) will fail.\n\n'

/** The vendored content for one source file: the banner (with its path filled in) plus the source verbatim. */
export function vendoredContent(pkg, file, source) {
  return HEADER.replace('%PKG%', pkg).replace('%FILE%', file) + source
}

/**
 * Compares the vendored tree against what the sources imply. `expected` and
 * `actual` are both `Map<relativePath, fileContent>` — `expected` built from the
 * package sources through {@link vendoredContent}, `actual` read off disk.
 * Returns the drift lines the `--check` mode prints (empty when in sync): a path
 * whose content differs or is missing, and a vendored path with no matching
 * source ("stale").
 */
export function vendorDrift(expected, actual) {
  const drift = []
  for (const [path, content] of expected) {
    if (actual.get(path) !== content) {
      drift.push(path)
    }
  }
  for (const path of actual.keys()) {
    if (!expected.has(path)) {
      drift.push(`${path} (stale — no longer in the package)`)
    }
  }
  return drift
}
